version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: James
      POSTGRES_PASSWORD: Miller
      POSTGRES_DB: medicationdb

  medication-app:
    image: stzymxrty/medicationtracker:v1.0
    ports:
      - "5005:5000"
    environment:
      SECRET_KEY: meddzz
      DATABASE_URL: postgresql://James:Miller@postgres:5432/medicationdb
    depends_on:
      - postgres